services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tenolo\Bundle\EntityBundle\EventListener\EntityListener: ~
    Tenolo\Bundle\EntityBundle\EventListener\DoctrineNullLoggerListener: ~
    Tenolo\Bundle\EntityBundle\EventListener\DnaAnnotationListener: ~
    Tenolo\Bundle\EntityBundle\Services\EntityDnaVerifier: ~

    # command
    Tenolo\Bundle\EntityBundle\Command\ResetDnaCommand: ~
