parameters:

    tenolo_entity.listener.entity.class: Tenolo\Bundle\EntityBundle\EventListener\EntityListener

    # repository
    tenolo_entity.default_repository.class: Tenolo\Bundle\EntityBundle\Repository\BaseEntityRepository

    # gedmo
    stof_doctrine_extensions.listener.softdeleteable.class: Tenolo\Bundle\EntityBundle\EventListener\SoftDeleteableListener

services:

    tenolo_entity.listener.entity:
        class: "%tenolo_entity.listener.entity.class%"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
